git:
  depth: 1
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install .
  - pip install codecov
script:
  - cd tests
  - coverage run test.py
after_success:
  - codecov
